language: node_js
node_js:
  - stable
script:
  - npm test
  - npm run build
after_success:
  # Report code coverage to coveralls
  - npm run coverage
  # Send build status to Discord
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  # Send build status to Discord
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
# before_deploy:
#   - openssl aes-256-cbc -K $encrypted_50d1e789a1c2_key -iv $encrypted_50d1e789a1c2_iv
#     -in secrets.tar.enc -out secrets.tar -d
#   - tar xvf secrets.tar
# deploy:
  # deploy master to staging
  # - provider: script
  #   script: bash scripts/deploy.sh
  #   on:
  #     branch: master
