language: node_js
node_js:
  - "18"
  - "10"

addons:
  ssh_known_hosts: possiblybad.com

before_install:
- git clone https://github.com/jhobz/nodecg.git
- mv nodecg ../
- cd ../nodecg
- npm i --production
- mv ../racecg bundles/
- mkdir cfg
- cd bundles/racecg
script:
- npm test
- npm run build
after_success:
- npm run coverage
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
before_deploy:
- openssl aes-256-cbc -K $encrypted_50d1e789a1c2_key -iv $encrypted_50d1e789a1c2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master