language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_33090a166214_key -iv $encrypted_33090a166214_iv
  -in gae-secret.json.enc -out gae-secret.json -d
after_success:
- npm run coverage
before_deploy:
- git clone https://github.com/nodecg/nodecg.git
- cd nodecg
- npm install --production
- ln -s ../dist bundles/racecg
deploy:
  provider: gae
  keyfile: gae-secret.json
  project: racecg
  skip_cleanup: true
